# Generated by Django 4.1.7 on 2023-04-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0004_allowedemail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AllowedEmail",
        ),
    ]
